---
- name: "update apt packages."
  become: true
  become_user: ubuntu
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  become_user: ubuntu
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  become_user: ubuntu
  apt:
    autoremove: yes

- name: "install dependencies"
  become: true
  become_user: ubuntu
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes

- name: "Install zip utility."
  become: true
  become_user: ubuntu
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  become_user: ubuntu
  npm:
    name: pm2
    global: yes
    production: yes
    state: present