---
- name: Copy backend compiled web server
  copy:
    src: /root/project/artifact.tar.gz 
    dest: /home/ubuntu
- name: extract backend files
  chdir: /home/ubuntu/
  shell: |
    tar xvf artifact.tar.gz

- name: Install node
  chdir: /home/ubuntu/
  shell: |
    npm install

- name: Build Node
  chdir: /home/ubuntu/
  shell: |
    npm run build

- name: stop pm2
  chdir: /home/ubuntu/
  shell: |
    pm2 stop default


- name: Start backend with pm2
  chdir: /home/ubuntu/
  shell: |
    pm2 start npm -- start

- name: save your list of processes
  chdir: /home/ubuntu/
  shell: |
    pm2 save  



